# Break-even breadth sensitivity for the sanctions paper.
#
# The break-even breadth p* solves  priv(pihat(1, p)) + omega*gam/2 = priv(0):
# the anticipated breadth at which routine weaponization stops paying. The
# referee requires this number to be reported as a scenario band, not a point.
# This script computes p* one-way in each unidentified parameter and the
# min/max band over the full grid, and writes macros to
# ../output/breakeven_numbers.tex.
#
# Run:  julia --project=. breakeven_sens.jl

include("solve_model.jl")   # reuses calib, ss, pihat_of; reruns main (fast)

# steady-state privilege at exposed loss rate pihat, for possibly non-baseline
# (mu, phi): rebuild ss with explicit mu.
function ss_mu(pihat::Float64, cb, mu::Float64)
    aE, aA = 0.5, 0.5
    for _ in 1:200_000
        N = mu * aE + (1.0 - mu) * aA
        cy = cb.l0 + cb.l1 * N
        aE2 = clamp((cy - pihat) / cb.kap, 0.0, 1.0)
        aA2 = clamp(cy / cb.kap, 0.0, 1.0)
        if abs(aE2 - aE) + abs(aA2 - aA) < 1e-15
            aE, aA = aE2, aA2
            break
        end
        aE = 0.5 * (aE + aE2)
        aA = 0.5 * (aA + aA2)
    end
    N = mu * aE + (1.0 - mu) * aA
    cy = cb.l0 + cb.l1 * N
    (N = N, priv = cy * N * W)
end

"Break-even breadth p* by bisection, given multiplier m, stakes gam,
severity phi, exposed mass mu."
function pstar(m::Float64, gam::Float64, phi::Float64, mu::Float64)
    cb = calib(m)
    base = ss_mu(0.0, cb, mu).priv
    f(p) = ss_mu(OMEGA * 1.0 * p * phi, cb, mu).priv + OMEGA * gam / 2.0 - base
    lo, hi = 1e-5, 1.0
    f(hi) > 0 && return NaN     # weapon never breaks even on [0,1]
    for _ in 1:200
        mid = 0.5 * (lo + hi)
        f(mid) > 0 ? (lo = mid) : (hi = mid)
    end
    0.5 * (lo + hi)
end

function main_sens()
    base = (m = 1.5, gam = 200.0, phi = 0.5, mu = 0.5)
    p0 = pstar(base.m, base.gam, base.phi, base.mu)

    ow = Dict(
        "m_1.0"   => pstar(1.0, base.gam, base.phi, base.mu),
        "m_2.5"   => pstar(2.5, base.gam, base.phi, base.mu),
        "gam_50"  => pstar(base.m, 50.0, base.phi, base.mu),
        "gam_800" => pstar(base.m, 800.0, base.phi, base.mu),
        "phi_0.25" => pstar(base.m, base.gam, 0.25, base.mu),
        "phi_0.75" => pstar(base.m, base.gam, 0.75, base.mu),
        "mu_0.3"  => pstar(base.m, base.gam, base.phi, 0.3),
        "mu_0.7"  => pstar(base.m, base.gam, base.phi, 0.7),
    )

    vals = Float64[]
    for m in [1.0, 1.5, 2.5], gam in [50.0, 200.0, 800.0],
        phi in [0.25, 0.5, 0.75], mu in [0.3, 0.5, 0.7]
        v = pstar(m, gam, phi, mu)
        isnan(v) || push!(vals, v)
    end
    lo, hi = extrema(vals)

    # reputation threshold: trigger equilibrium sustains s_R iff
    # beta_H/(1-beta_H) >= gam / (omega*gam - 2*l1*omega^2*c^2*W),
    # i.e. beta_H >= T/(1+T). Computed at baseline and across gamma.
    function beta_rep(m, gam, phi, mu, p)
        cb = calib(m)
        c = mu * p * phi / (cb.kap - cb.l1)
        denom = OMEGA * gam - 2.0 * cb.l1 * OMEGA^2 * c^2 * W
        denom <= 0 && return NaN
        T = gam / denom
        T / (1.0 + T)
    end
    brep = beta_rep(base.m, base.gam, base.phi, base.mu, PSING)
    brep_rout = beta_rep(base.m, base.gam, base.phi, base.mu, 0.25)

    println("baseline p* = ", round(p0 * 100, digits = 2), "%")
    for (k, v) in sort(collect(ow))
        println(k, ": ", round(v * 100, digits = 2), "%")
    end
    println("band: ", round(lo * 100, digits = 1), "% to ", round(hi * 100, digits = 1), "%")

    fmtp(x; d = 1) = string(round(x * 100, digits = d))
    lines = String[
        "% generated by breakeven_sens.jl",
        "\\newcommand{\\PBEbase}{$(fmtp(p0))}",
        "\\newcommand{\\PBEmLow}{$(fmtp(ow["m_1.0"]))}",
        "\\newcommand{\\PBEmHigh}{$(fmtp(ow["m_2.5"]))}",
        "\\newcommand{\\PBEgamLow}{$(fmtp(ow["gam_50"]))}",
        "\\newcommand{\\PBEgamHigh}{$(fmtp(ow["gam_800"]))}",
        "\\newcommand{\\PBEphiLow}{$(fmtp(ow["phi_0.25"]))}",
        "\\newcommand{\\PBEphiHigh}{$(fmtp(ow["phi_0.75"]))}",
        "\\newcommand{\\PBEmuLow}{$(fmtp(ow["mu_0.3"]))}",
        "\\newcommand{\\PBEmuHigh}{$(fmtp(ow["mu_0.7"]))}",
        "\\newcommand{\\PBELo}{$(fmtp(lo))}",
        "\\newcommand{\\PBEHi}{$(fmtp(hi))}",
        "\\newcommand{\\BetaRepBase}{$(round(brep, digits = 3))}",
        "\\newcommand{\\BetaRepRoutine}{$(round(brep_rout, digits = 3))}",
        "\\newcommand{\\RateRepBase}{$(round((1.0 - brep) / brep * 100, digits = 1))}",
    ]
    open(joinpath(OUTDIR, "breakeven_numbers.tex"), "w") do f
        for l in lines
            println(f, l)
        end
    end
    println("saved breakeven_numbers.tex")
end

main_sens()
