# Break-even breadth sensitivity for the sanctions paper.
#
# The break-even breadth p* solves  priv(pihat(1, p)) + omega*gam/2 = priv(0):
# the anticipated breadth at which routine weaponization stops paying. The
# The paper reports this number as a sensitivity band. This script computes p*
# one-way in each unidentified parameter and the
# min/max band over the full grid, and writes macros to
# ../output/breakeven_numbers.tex.
#
# Run:  julia --project=. breakeven_sens.jl

include("solve_model.jl")

"Break-even breadth p* by bisection, given multiplier m, stakes gam,
severity phi, exposed mass mu."
function pstar(m::Float64, gam::Float64, phi::Float64, mu::Float64;
               zeta::Float64 = ZETA_H, chi::Float64 = CHI0,
               convenience::Symbol = :logistic,
               cost::Symbol = :cubic)
    gc = global_calib(m; convenience = convenience, cost = cost)
    break_even_breadth(
        gc; gam = gam, zeta = zeta, chi = chi, mu = mu, phi = phi)
end

function main_sens()
    base = (m = 1.5, gam = 200.0, phi = 0.5, mu = 0.5,
            zeta = ZETA_H, chi = CHI0)
    p0 = pstar(base.m, base.gam, base.phi, base.mu;
               zeta = base.zeta, chi = base.chi)

    ow = Dict(
        "m_1.0"   => pstar(1.0, base.gam, base.phi, base.mu),
        "m_2.5"   => pstar(2.5, base.gam, base.phi, base.mu),
        "gam_50"  => pstar(base.m, 50.0, base.phi, base.mu),
        "gam_800" => pstar(base.m, 800.0, base.phi, base.mu),
        "phi_0.25" => pstar(base.m, base.gam, 0.25, base.mu),
        "phi_0.75" => pstar(base.m, base.gam, 0.75, base.mu),
        "mu_0.3"  => pstar(base.m, base.gam, base.phi, 0.3),
        "mu_0.7"  => pstar(base.m, base.gam, base.phi, 0.7),
        "zeta_0.25" => pstar(base.m, base.gam, base.phi, base.mu; zeta = 0.25),
        "zeta_1.0" => pstar(base.m, base.gam, base.phi, base.mu; zeta = 1.0),
        "chi_2.0" => pstar(base.m, base.gam, base.phi, base.mu; chi = 2.0),
        "chi_4.0" => pstar(base.m, base.gam, base.phi, base.mu; chi = 4.0),
    )

    vals = Float64[]
    for m in [1.0, 1.5, 2.5], gam in [50.0, 200.0, 800.0],
        phi in [0.25, 0.5, 0.75], mu in [0.3, 0.5, 0.7]
        v = pstar(m, gam, phi, mu)
        isnan(v) || push!(vals, v)
    end
    lo, hi = extrema(vals)

    closures = Dict{String,Float64}()
    closure_shares = Float64[]
    closure_root_counts = Int[]
    for convenience in (:logistic, :hill, :power)
        for cost in (:quadratic, :cubic, :quintic)
            key = "$(convenience)_$(cost)"
            closures[key] = pstar(
                base.m, base.gam, base.phi, base.mu;
                zeta = base.zeta, chi = base.chi,
                convenience = convenience, cost = cost)
            alternative = global_calib(
                base.m; convenience = convenience, cost = cost)
            routine_wedge = sanctions_wedge(
                1.0, 0.25; phi = base.phi, chi = base.chi)
            push!(closure_shares,
                  global_ss(routine_wedge, alternative).N)
            push!(closure_root_counts,
                  length(global_roots(routine_wedge, alternative)))
        end
    end

    # reputation threshold: trigger equilibrium sustains s_R iff
    # beta_H/(1-beta_H) >= gam / (omega*gam - 2*l1*omega^2*c^2*W),
    # i.e. beta_H >= T/(1+T). Computed at baseline and across gamma.
    function beta_rep(m, gam, phi, mu, p; zeta = ZETA_H, chi = CHI0)
        cb = calib(m)
        c = mu * p * phi * chi / (cb.kap - cb.l1)
        denom = OMEGA * gam - 2.0 * zeta * cb.l1 * OMEGA^2 * c^2 * W
        denom <= 0 && return NaN
        T = gam / denom
        T / (1.0 + T)
    end
    brep = beta_rep(base.m, base.gam, base.phi, base.mu, PSING)
    brep_rout = beta_rep(base.m, base.gam, base.phi, base.mu, 0.25)

    println("baseline p* = ", round(p0 * 100, digits = 2), "%")
    for (k, v) in sort(collect(ow))
        println(k, ": ", round(v * 100, digits = 2), "%")
    end
    println("band: ", round(lo * 100, digits = 1), "% to ", round(hi * 100, digits = 1), "%")

    fmtp(x; d = 1) = string(round(x * 100, digits = d))
    lines = String[
        "% generated by breakeven_sens.jl",
        "\\newcommand{\\PBEbase}{$(fmtp(p0))}",
        "\\newcommand{\\PBEmLow}{$(fmtp(ow["m_1.0"]))}",
        "\\newcommand{\\PBEmHigh}{$(fmtp(ow["m_2.5"]))}",
        "\\newcommand{\\PBEgamLow}{$(fmtp(ow["gam_50"]))}",
        "\\newcommand{\\PBEgamHigh}{$(fmtp(ow["gam_800"]))}",
        "\\newcommand{\\PBEphiLow}{$(fmtp(ow["phi_0.25"]))}",
        "\\newcommand{\\PBEphiHigh}{$(fmtp(ow["phi_0.75"]))}",
        "\\newcommand{\\PBEmuLow}{$(fmtp(ow["mu_0.3"]))}",
        "\\newcommand{\\PBEmuHigh}{$(fmtp(ow["mu_0.7"]))}",
        "\\newcommand{\\PBEzetaLow}{$(fmtp(ow["zeta_0.25"]))}",
        "\\newcommand{\\PBEzetaHigh}{$(fmtp(ow["zeta_1.0"]))}",
        "\\newcommand{\\PBEchiTwo}{$(fmtp(ow["chi_2.0"]))}",
        "\\newcommand{\\PBEchiFour}{$(fmtp(ow["chi_4.0"]))}",
        "\\newcommand{\\PBELo}{$(fmtp(lo))}",
        "\\newcommand{\\PBEHi}{$(fmtp(hi))}",
        "\\newcommand{\\BetaRepBase}{$(round(brep, digits = 3))}",
        "\\newcommand{\\BetaRepRoutine}{$(round(brep_rout, digits = 3))}",
        "\\newcommand{\\RateRepBase}{$(round((1.0 - brep) / brep * 100, digits = 1))}",
        "\\newcommand{\\PBELogQuadratic}{$(fmtp(closures["logistic_quadratic"]))}",
        "\\newcommand{\\PBELogCubic}{$(fmtp(closures["logistic_cubic"]))}",
        "\\newcommand{\\PBELogQuintic}{$(fmtp(closures["logistic_quintic"]))}",
        "\\newcommand{\\PBEHillQuadratic}{$(fmtp(closures["hill_quadratic"]))}",
        "\\newcommand{\\PBEHillCubic}{$(fmtp(closures["hill_cubic"]))}",
        "\\newcommand{\\PBEHillQuintic}{$(fmtp(closures["hill_quintic"]))}",
        "\\newcommand{\\PBEPowerQuadratic}{$(fmtp(closures["power_quadratic"]))}",
        "\\newcommand{\\PBEPowerCubic}{$(fmtp(closures["power_cubic"]))}",
        "\\newcommand{\\PBEPowerQuintic}{$(fmtp(closures["power_quintic"]))}",
        "\\newcommand{\\PBEClosureLow}{$(fmtp(minimum(values(closures))))}",
        "\\newcommand{\\PBEClosureHigh}{$(fmtp(maximum(values(closures))))}",
        "\\newcommand{\\NClosureLow}{$(fmtp(minimum(closure_shares)))}",
        "\\newcommand{\\NClosureHigh}{$(fmtp(maximum(closure_shares)))}",
        "\\newcommand{\\ClosureMaxRoots}{$(maximum(closure_root_counts))}",
    ]
    open(joinpath(OUTDIR, "breakeven_numbers.tex"), "w") do f
        for l in lines
            println(f, l)
        end
    end
    println("saved breakeven_numbers.tex")
end

main_sens()
