# Dispersion and consumed-distance sensitivity for the fragmentation paper.
#
# Two referee questions this script answers with computation rather than
# assertion. First, is the fold an artifact of too little heterogeneity? The
# premium dispersion s smooths the sector map, so enough dispersion must kill
# the fold: this script finds where. Second, the headline "the 2022
# reassessment consumed two thirds of the distance to the fold" is a point
# estimate on the (theta, chi) grid of the sensitivity table: this script
# reports the consumed share across that grid as a band.
#
# Self-contained reimplementation of the sector fixed-point scan in
# solve_model.jl, parameterized by (theta, chi, sln). The baseline cell must
# reproduce the published band [0.114, 0.131] before anything else is trusted.
#
# Run:  julia --project=. dispersion_sens.jl     (~1 min)

using SpecialFunctions: erf

const OUTDIR = joinpath(@__DIR__, "..", "output")

const W_M  = [0.15, 0.35, 0.50]
const SIGM = [2.0, 4.0, 8.0]
const SSH  = [0.50, 0.35, 0.20]
const DUR  = [1.5, 1.0, 0.5]
const GMED = [0.20, 0.15, 0.10]
const F0NG = [0.05, 0.08, 0.10]
const ETAA = 0.01
const XI   = 0.4
const DELTA_PRE  = 0.04
const DELTA_POST = 0.10

lam0(m) = ((1.0 - SSH[m])^(1.0 / (1.0 - SIGM[m])) - 1.0) * DUR[m]
const LAM0 = [lam0(m) for m in 1:3]

ncdf(z) = 0.5 * (1.0 + erf(z / sqrt(2.0)))
Hcdf(g, m, sln) = g <= 0.0 ? 0.0 : ncdf((log(g) - log(GMED[m])) / sln)

function ghat(Fm, F, m, del, theta, chi, sln)
    pim = del * (1.0 - theta * (1.0 - Fm)) + ETAA * F
    pim * LAM0[m] * (1.0 + XI * Fm) / (1.0 - chi * Fm)
end

Tmap(Fm, F, m, del, theta, chi, sln) =
    F0NG[m] + (1.0 - F0NG[m]) * Hcdf(ghat(Fm, F, m, del, theta, chi, sln), m, sln)

"Given the critical sector at Fc, solve sectors 2 and 3 and the aggregate."
function others(Fc, del, theta, chi, sln)
    F2, F3 = 0.1, 0.1
    F = W_M[1] * Fc + W_M[2] * F2 + W_M[3] * F3
    for _ in 1:20_000
        F2n = Tmap(F2, F, 2, del, theta, chi, sln)
        F3n = Tmap(F3, F, 3, del, theta, chi, sln)
        Fn = W_M[1] * Fc + W_M[2] * F2n + W_M[3] * F3n
        if abs(F2n - F2) + abs(F3n - F3) < 1e-13
            F2, F3, F = F2n, F3n, Fn
            break
        end
        F2, F3, F = 0.5 * (F2 + F2n), 0.5 * (F3 + F3n), Fn
    end
    W_M[1] * Fc + W_M[2] * F2 + W_M[3] * F3
end

"Number of critical-sector equilibria at dispute hazard del."
function nroots(del, theta, chi, sln)
    grid = range(F0NG[1], 1.0, length = 2001)
    resid = [Tmap(Fc, others(Fc, del, theta, chi, sln), 1, del, theta, chi, sln) - Fc
             for Fc in grid]
    n = 0
    for i in 1:length(grid)-1
        if resid[i] == 0.0 || resid[i] * resid[i+1] < 0.0
            n += 1
        end
    end
    n
end

"Fold band [dlo, dhi]: hazards with three or more equilibria (NaN if none)."
function foldband(theta, chi, sln; dgrid = 0.02:0.0005:0.30)
    multi = [d for d in dgrid if nroots(d, theta, chi, sln) >= 3]
    isempty(multi) ? (NaN, NaN) : (first(multi), last(multi))
end

function main()
    # 1. reproduce the published baseline band
    base = foldband(0.6, 0.4, 0.5)
    println("baseline band (expect ~0.114-0.131): ", base)
    @assert abs(base[1] - 0.114) < 0.002 && abs(base[2] - 0.131) < 0.002

    # 2. dispersion sweep at baseline (theta, chi)
    svals = [0.3, 0.4, 0.5, 0.7, 0.9, 1.1]
    bands = Dict{Float64,Tuple{Float64,Float64}}()
    for s in svals
        bands[s] = foldband(0.6, 0.4, s)
        println("s = ", s, " band = ", bands[s])
    end
    sgone = NaN
    for s in svals
        if isnan(bands[s][1]) && s > 0.5
            sgone = s
            break
        end
    end

    # 3. consumed distance across the (theta, chi) grid of the paper's table
    consumed = Float64[]
    past = 0
    for th in [0.4, 0.5, 0.6, 0.7], ch in [0.0, 0.2, 0.4, 0.6]
        b = foldband(th, ch, 0.5)
        isnan(b[2]) && continue
        c = (DELTA_POST - DELTA_PRE) / (b[2] - DELTA_PRE)
        push!(consumed, c)
        c >= 1.0 && (past += 1)
        println("theta=", th, " chi=", ch, " fold_hi=", b[2],
                " consumed=", round(100c, digits = 1), "%")
    end
    clo, chi_ = extrema(consumed)

    fmt(x; d = 0) = string(round(x, digits = d))
    lines = String[
        "% generated by dispersion_sens.jl",
        "\\newcommand{\\SFoldGoneVal}{$(isnan(sgone) ? "none" : fmt(sgone; d = 1))}",
        "\\newcommand{\\FoldHiSPointSeven}{$(isnan(bands[0.7][2]) ? "none" : fmt(100 * bands[0.7][2]; d = 1))}",
        "\\newcommand{\\FoldHiSPointNine}{$(isnan(bands[0.9][2]) ? "none" : fmt(100 * bands[0.9][2]; d = 1))}",
        "\\newcommand{\\ConsumedLoPct}{$(fmt(100clo))}",
        "\\newcommand{\\ConsumedHiPct}{$(fmt(100 * min(chi_, 1.0)))}",
        "\\newcommand{\\CellsPastFold}{$(past)}",
    ]
    open(joinpath(OUTDIR, "dispersion_numbers.tex"), "w") do f
        for l in lines
            println(f, l)
        end
    end
    println("saved dispersion_numbers.tex")
end

main()
